### ISSUE TITLE
'NoneType' object has no attribute 'attrs'

### ISSUE THREAD

**Issue by MilkKoun** [Roblox-Thot/DecalUploader#1]
veri = **soup.find("input", {"name" : "__RequestVerificationToken"}).attrs**["Value"] #parse out the verification token from the HTML
AttributeError: 'NoneType' object has no attribute 'attrs'

Something wrong right here

**Comment by Roblox-Thot** [comment]
Looks like Roblox removed the endpoint that the script used.

I'll look into updating it i guess lol

**Comment by Roblox-Thot** [comment]
Fixed in the newest commits.

If you have any new issues feel free to open a new Issue thingy
