### ISSUE TITLE
Rate limiting

### ISSUE THREAD

**Issue by Roblox-Thot** [Roblox-Thot/DecalUploader#10]
Accounts get rate limited after ~5-6 uploads

## Current ideas
1. #8 Threading per cookie (will require fast computers/optimization)
2. Random cookies per upload (implemented in `MassCookieUpload.py` just kinda shit)

If anyone has a better idea feel free to let me know.

## Current WIP
[Roblox-Thot/DecalUploaderV2](https://github.com/Roblox-Thot/DecalUploaderV2) is a WIP of using rblxopencloud in python

**Comment by MilkKoun** [comment]
Dm me .skey.

**Comment by ssynical** [comment]
u can probably merge code from seranok's upload enhancer to upload like 200 images at once

**Comment by Roblox-Thot** [comment]
> u can probably merge code from seranok's upload enhancer to upload like 200 images at once

If you are talking about the like 2018 extension that's on the chrome store, then I can't since that one uses an outdated API that Roblox removed about a year ago.

**Comment by ssynical** [comment]
yeah ur right. thanks

**Comment by Roblox-Thot** [comment]
Fixed enough to upload ~60-90 or sometimes 100 on a good day
