### ISSUE TITLE
help Out.csv

### ISSUE THREAD

**Issue by Cludration** [Roblox-Thot/DecalUploader#12]
Uh, can you make it when it asks you if you want to delete the old "out.csv" and you type "N" and it makes a new "out.csv" like "out_1.csv" or anything like that that can work, please? After I uploaded it, it became a mess to check the ids in the masscookieuploader, and I could not use the checker because there was no output.

**Comment by Roblox-Thot** [comment]
Do to me being mostly lazy, na not really unless someone makes a pull request to add it, I would just rename the old ones after your done to be something like "`R63 out.csv`" so you don`t overwrite the old ones.

Or just use [DecalUploaderV2](https://github.com/Roblox-Thot/DecalUploaderV2) which just uploads to webhooks
