### ISSUE TITLE
Timeout

### ISSUE THREAD

**Issue by MilkKoun** [Roblox-Thot/DecalUploader#7]
requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='auth.roblox.com', port=443): Max retries exceeded with url: /v2/login (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000020BE2CEF2F0>, 'Connection to auth.roblox.com timed out. (connect timeout=None)'))

**Comment by MilkKoun** [comment]
this error appears sometimes, considering that it is not critical

**Comment by Roblox-Thot** [comment]
If you are using proxies I think that may be a proxy issue if I'm not mistaken.

**Comment by MilkKoun** [comment]
Maybe, but yea i have proxy
