### ISSUE TITLE
multithreading

### ISSUE THREAD

**Issue by ssynical** [Roblox-Thot/DecalUploader#8]
please do add proxy support or multithreading to prevent rate limitation 🙏🙏

**Comment by Roblox-Thot** [comment]
I may at some point but since this could be used as a module so could anyone else.

Might do it sometime next week tho

**Comment by ssynical** [comment]
thank you i luv dis program !!!! thanks

**Comment by Roblox-Thot** [comment]
Sorry I kinda lost motivation to add it after the Decal filter started banning quicker.

If someone wants to make a Pull request with something like that though I'd merge it.

**Comment by ssynical** [comment]
ya no worries the tool itself is great, especially after api change
